### ISSUE TITLE
shell returned 1

### ISSUE THREAD

**Issue by SingularisArt** [pavanbhat1999/figlet.nvim#4]
Hello.

When I run: `FigComment Death.NeoVim`, the command returns this:

```bash
shell returned 1
```

**Comment by pavanbhat1999** [comment]
@SingularisArt  Do you have Comment. nvim installed? 

To make comments in any file type I added comment.nvim as dependecy. 


Ya in installation also I will change require option

**Comment by SingularisArt** [comment]
Yes. I have it installed.

**Comment by pavanbhat1999** [comment]
@SingularisArt  Do you have figlet and fonts installed into figlet

Just to be sure run following command in terminal .
`figlet -f ANSI\ Regular NEOVIM`

Is this command working

**Comment by SingularisArt** [comment]
This is the error that I got:

```bash
figlet: ANSI Regular: Unable to open font file
```

**Comment by pavanbhat1999** [comment]
> This is the error that I got:
> 
> ```shell
> figlet: ANSI Regular: Unable to open font file
> ```
@SingularisArt  
You dont have font installed so do use commands
git clone https://github.com/xero/figlet-fonts.git
cp  figlet-fonts/* /usr/share/figlet/fonts/

**Comment by pavanbhat1999** [comment]
![issue](https://user-images.githubusercontent.com/47946571/150902840-765df662-1159-4de7-ad76-50db572f022a.gif)
It works

**Comment by SingularisArt** [comment]
Awesome! Thanks so much!
