### ISSUE TITLE
Superfluous dd?

### ISSUE THREAD

**Issue by eschmidscs** [pavanbhat1999/figlet.nvim#5]
Hi

On my side, the FigComment command always left the figlet with the last line missing.
Some digging showed this dd in the FigComment function. If I remove it, it works fine.

Did you require the dd on your side? Might that be configuration dependent?

Best regards,
emanuel

**Comment by pavanbhat1999** [comment]
It was my personal preference at that time to remove that. 

Now it is fixed. #6 

Thanks for the suggestion

**Comment by pavanbhat1999** [comment]
Done
